# Generated by Django 3.1.2 on 2020-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=255)),
                ('airport_city', models.CharField(max_length=255)),
                ('airport_country', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'airport',
                'managed': False,
            },
        ),
    ]
