# Generated by Django 3.1.2 on 2020-10-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledFlight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_code', models.CharField(max_length=255)),
                ('flight_dep_date', models.DateField()),
                ('flight_dep_time', models.TimeField()),
                ('flight_arrival_date', models.DateField()),
                ('flight_arrival_time', models.TimeField()),
                ('flight_cost', models.FloatField()),
            ],
            options={
                'db_table': 'scheduled_flight',
                'managed': False,
            },
        ),
    ]
