# Generated by Django 3.1.2 on 2020-10-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_routes', '0002_scheduledflight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledFlight',
        ),
    ]
